CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38683630, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15372086, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23348849, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46562941, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53711628, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45195040, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45915973, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22819047, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18669024, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54344183, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13476816, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43619385, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12289844, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28657140, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34752130, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18458302, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24373968, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42660402, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16133502, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54424719, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16578900, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24293401, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28620676, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12710483, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34044385, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26853481, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23826754, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41453105, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13841047, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49156814, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25783590, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21948059, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41201926, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39616109, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36076908, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31434519, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15935088, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41415145, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24673243, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34969602, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25648245, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33826718, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17846041, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52016720, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48855409, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29164982, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24701810, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15902338, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25857179, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22488626, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46036976, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51060491, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24479732, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32653334, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29390149, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51960041, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14755459, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17407302, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51758074, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18063238, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17755305, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49086667, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49672541, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14981440, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22458774, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27677236, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47006166, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33640302, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41027615, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28418966, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56131443, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16976706, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45733820, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36386678, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22468385, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28800602, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35787986, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53036294, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25047255, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21841071, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46780636, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19969996, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51800637, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36565280, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47444403, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25417947, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48702187, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19827035, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55999539, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12530930, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17902722, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51227792, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39555503, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44110910, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54194281, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13110595, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11839191, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33115325, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57296074, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43410125, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27151606, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54908797, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34765044, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35293610, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14220422, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15228748, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51025148, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25410745, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58812328, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28949163, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31027667, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57335911, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15656418, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51288136, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11669908, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43363374, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24272207, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54304222, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56297566, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13079149, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46263187, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43678674, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13941453, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46458382, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21453886, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56667383, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49020972, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56978665, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46508420, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54876384, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42384464, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29993626, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41573824, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17626057, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11959854, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43588926, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35364811, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37680546, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26592596, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39663061, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54423969, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56266745, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17491349, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51781683, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59732884, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47270662, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29007398, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58023125, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59520663, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51633480, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32873384, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39627178, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54689062, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22122383, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21620453, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56633510, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12627341, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28213724, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44785844, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37672290, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51834955, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42049751, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22956657, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27050525, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55127318, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22756590, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26073629, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48632372, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21817139, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36967543, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59736896, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57418339, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38189214, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25693256, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11425304, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36708545, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33300291, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27643087, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55725588, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43439133, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14949597, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12599633, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19590333, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52006620, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49699664, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19369405, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55278927, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23026786, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15380536, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53248443, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47133024, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29260176, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45616608, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36138122, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31662188, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11784360, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56866678, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27558834, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51187782, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24363595, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27998339, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26549925, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21385552, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12917742, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57742095, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52879986, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45511678, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25630892, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16229878, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35960522, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13437642, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28751881, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27072723, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29784554, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13303714, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44973502, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46930685, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52363898, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32527066, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16285171, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23210727, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52245064, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27475820, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15305156, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13635143, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28292780, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23271274, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18537332, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18116334, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39542439, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29079983, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47141659, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52047234, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58404739, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15995989, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48162553, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48528569, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23638610, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43891808, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13563722, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54618675, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45600764, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49722316, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31222053, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15367005, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46700751, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56976015, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38691118, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42384044, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31626085, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21957644, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35054420, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49145538, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38471328, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18643018, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36461050, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36181533, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15734444, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51648160, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32685002, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49323390, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29052735, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29879995, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25971167, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39803631, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43529126, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31650660, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18572356, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59261425, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36681630, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14614940, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52021789, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49031628, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55319016, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52799742, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29665566, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33632551, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52476754, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35665297, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14173615, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24346212, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53406657, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11923798, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59416781, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48978885, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53840095, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45209869, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23823116, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13835824, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57322609, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56363864, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14343842, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39305918, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51458783, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29749289, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31550210, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14877944, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49548522, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46611176, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27609255, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23115236, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44638924, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14247153, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34699956, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23440394, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59725043, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38643729, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13076119, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19132573, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19522324, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43537610, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35242081, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48069872, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46945741, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53467057, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12390053, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36490118, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19054666, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38060420, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14441749, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58993798, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28048898, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43484843, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44323505, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16526515, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35616989, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39447120, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18953879, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48657936, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28558910, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35377850, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49052662, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42510358, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45672462, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18878196, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31485825, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13275357, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13184047, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48767737, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25405037, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23339743, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23956802, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53906607, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42760119, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26333009, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24913984, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42225941, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39964544, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21337903, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38824903, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37192616, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55432317, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21534927, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33210509, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32087014, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46688915, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26696209, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17098719, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38144911, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54339180, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57880950, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41389902, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11451197, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27027869, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18743208, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12116429, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55798729, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25630030, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38592762, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56353394, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19270284, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17333814, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44609195, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29407813, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36051394, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38749220, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12895520, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18896752, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59180679, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51957626, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29495737, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24934586, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14561844, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16331025, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49461910, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24000373, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23647211, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54606486, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47436000, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17885237, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35813630, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55470941, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27050553, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16922266, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27205734, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41122902, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53317652, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29739054, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36696514, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17562631, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34144644, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36440420, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17186146, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13345203, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44577259, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58496483, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44717299, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25696957, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16422971, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43538313, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31549821, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31282471, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21771341, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58122446, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44719758, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51760069, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36095308, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18796001, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47221611, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52664882, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42727488, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32313580, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37128954, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32120606, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21792971, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11308449, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44226696, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59204883, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51299939, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42671346, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32419699, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54773001, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38778043, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44075342, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44873544, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23257034, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29001833, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36669460, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29235973, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33432074, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53792165, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39507443, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15290907, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33620685, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53157484, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22539310, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38925119, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35645843, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17819599, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18869692, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26766058, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26478768, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18042567, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33523099, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29151147, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21811646, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23431436, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39529180, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59555286, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57386590, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28131485, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12857457, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48808882, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28602690, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48571895, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12190322, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55716238, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51812741, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39933262, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14474295, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22032970, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31407443, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53444598, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31274410, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25336787, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46464533, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25503724, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42338976, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51229029, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15965849, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18942662, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36382622, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48023484, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37063556, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46512952, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58418829, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51494030, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41613088, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11102491, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18554411, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45498979, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38585103, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47880372, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26202822, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24780070, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31063657, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46641830, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54342903, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45236468, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13821239, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52493184, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11832187, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55934462, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24019269, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51448661, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55928841, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48032273, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11050571, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17623265, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58398069, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57840306, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59387029, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22708452, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11594347, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12095546, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21851262, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12856243, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22216485, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26652615, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53692602, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16480846, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47143237, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56377164, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18665028, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42080246, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31444829, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36034522, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34225779, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48878297, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12823270, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28344014, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38287810, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16397011, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34761076, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43079450, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29649146, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11613993, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25580942, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37238028, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21445358, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31036230, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33036743, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49822910, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47139404, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17515622, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23453872, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22928894, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49481790, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11910583, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31715820, "t", 1, "f" );
