CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52532366, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51569710, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29725033, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14729622, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18615863, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35799181, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49201065, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43000572, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29947887, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18155116, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44726878, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57122100, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42049983, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13309166, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36852009, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11488348, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19064051, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37466459, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13700453, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19759303, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15688459, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31357195, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38737605, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46646385, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25518012, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15582908, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55954145, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27906293, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16131093, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33958422, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38853613, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54974736, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39605538, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32070223, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27889247, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43105085, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43581122, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58348757, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36141064, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52206420, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57538832, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37928461, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35477357, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37693444, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58420472, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25410610, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47133682, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47833153, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34923173, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58819865, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13345178, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16778459, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29837939, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22167125, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21652842, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45163560, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22236447, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56674641, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27847736, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11679111, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54984682, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55994937, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38168189, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52219306, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43750797, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24980109, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29317381, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21979698, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15504269, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58348406, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59884635, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24188757, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15477981, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16185163, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47253436, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25305778, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27285584, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27489023, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28507983, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54412116, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41496911, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44348573, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38531453, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12695924, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16571548, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51078145, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25927025, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46800173, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32686539, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13192616, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54669367, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37251844, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44120054, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25727435, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21357642, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46609012, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45639844, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29295711, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29860203, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25806675, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45790779, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47298513, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16823860, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17839824, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37266483, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39905120, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18058730, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44025795, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24497956, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41851666, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31121239, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14133710, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36130283, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42699576, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38981133, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43577446, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51211723, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48140543, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16924214, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25871983, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33151923, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12920769, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29646887, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47449704, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14216229, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31228392, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26986274, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51684495, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22184931, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58718568, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55377771, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26930065, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32255271, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54976659, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56364034, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41167023, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55699652, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13131551, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51321079, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56412908, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49517262, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43363540, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19411046, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33728463, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46749226, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21666415, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47979098, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24731483, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16761793, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25617189, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16684614, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15776911, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12194146, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11973696, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38223985, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15974456, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35333896, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22367016, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52647606, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59919705, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36281206, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45752208, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31854654, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15827473, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37185239, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57540429, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16819407, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36495196, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17536810, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31547710, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23975092, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44322614, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37944148, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33829209, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25506782, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14701373, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32734287, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27584843, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48730724, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47539753, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13175468, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35212214, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52834887, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52072910, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38638049, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41603847, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48707002, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14149698, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35130925, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47056713, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21259422, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36892716, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43908431, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57852335, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27015523, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54965226, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14803793, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38651978, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11498761, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39153751, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45700603, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35330509, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23242235, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31265295, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15695698, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34681901, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17460255, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32747862, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12761335, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45819444, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47742514, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39865007, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53307728, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27182182, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59461106, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42809329, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56019469, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27541297, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37157131, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37628186, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58635015, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14455033, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15365433, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12010025, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58458417, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46017231, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17508176, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22614394, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55365372, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31246033, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48159081, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15378466, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32595677, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46514251, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46110207, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37107170, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59158064, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27553624, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22350861, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56637936, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21241336, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13653072, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37014163, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26593330, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47029603, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54194015, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35839420, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54058045, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56910897, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34711388, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47773062, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15600798, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17992553, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37697995, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21237650, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17072242, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58382244, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28316201, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24782501, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23250456, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35310359, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13805784, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25689332, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17509863, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27668873, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14209773, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59094892, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41204956, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31153894, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29484207, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22382573, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32865464, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39081158, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23477551, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49644625, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45739636, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13099004, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14658120, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58844648, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23362540, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47284451, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22212003, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55570589, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55077082, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18425016, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19391139, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17414137, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51670725, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58063393, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54019019, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51167128, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41657462, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59604148, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24226537, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59342550, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15546275, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42393582, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38349539, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46853534, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16879922, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34289626, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21063320, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41875511, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17990163, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24420571, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54356479, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45501233, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34812124, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54266260, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54866977, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14553253, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51528714, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56542727, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46486333, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55850501, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44407911, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53544926, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19944489, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58804527, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19381067, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19548998, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15231630, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22301177, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15115149, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18082199, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42668965, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33444188, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25728489, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16770883, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57810329, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28239025, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15608405, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17868051, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49713301, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46783280, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43616521, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56512392, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58779093, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16524363, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49628465, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31495442, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13704374, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15457117, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27722368, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57820786, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12940226, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26516639, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56463424, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31290119, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48456289, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14385999, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55737517, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11208500, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52439453, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15598773, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33827740, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47520033, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25657391, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49607647, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47532426, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44331704, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53864978, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58844955, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47895836, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13651933, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39716640, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11135969, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23377640, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37850438, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36337649, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36286234, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21540162, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11896341, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17529358, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51060021, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42836495, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31612757, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47396733, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28559378, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47059812, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25430343, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49966998, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28524711, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17888295, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46045862, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26043896, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44724886, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52732194, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37449245, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41053317, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43416436, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19917482, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12798069, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26910150, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44077685, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23816585, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56919508, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54551150, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26168082, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45957274, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57582162, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36755952, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52504105, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22258407, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14416308, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55902415, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18787109, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42817051, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58137295, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13895963, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39870793, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13258018, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43881764, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19963011, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55297139, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52682103, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46594437, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22500707, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55889409, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15868720, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13963394, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23681883, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12171386, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31429497, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29860504, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58370970, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18312122, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35084156, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39691056, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31623293, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39024124, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34217423, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25301211, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11844100, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35124724, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48088476, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38657267, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25798985, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39460269, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39171094, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21059070, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48708404, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24530162, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54871221, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19199698, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31747429, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49257111, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57146011, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52715316, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37395151, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37846188, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45708752, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48814077, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48170837, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59275941, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41173945, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12479970, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11190274, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14998350, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27625346, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13624732, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55963188, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14186892, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44722850, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22634845, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26332986, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28321248, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42043484, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12048026, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15604578, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56474722, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37814391, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16976217, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15219818, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57769754, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24850227, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42850663, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21163253, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57016377, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52970681, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57729100, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24672352, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57356789, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58848036, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21534870, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14860846, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11062798, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43667655, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26590015, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17737476, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57133301, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42666597, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53195397, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28001183, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31889493, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11278727, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18519782, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41731759, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28709383, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47106481, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57609754, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16671164, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38635655, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59023621, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43617036, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14403262, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46681058, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26450544, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52343814, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54233708, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34029709, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38357277, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26721307, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34170982, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41823104, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48094285, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49578264, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19817399, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51085823, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17073478, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32069709, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41820130, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33388560, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46829028, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57343267, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38767472, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45386512, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14023163, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54105313, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33967302, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35009992, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55151830, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54484303, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48175279, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35420837, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25029683, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24388579, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25457579, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14733756, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39399507, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53078169, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22539570, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55842697, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23764029, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15210301, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38369789, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19023425, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47706239, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39749958, "t", 1, "f" );
INSERT INTO Alumno (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37865839, "t", 1, "f" );
