CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31823429, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11269671, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51984441, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13031929, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47504328, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45682039, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18007076, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37384665, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56043301, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28526844, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43480687, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43371664, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31811810, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18663622, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37709788, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56375138, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49426651, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44653419, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12597641, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29819646, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42178576, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24141860, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15177292, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32477097, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55915125, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27151026, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42543729, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58812550, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46667818, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41206982, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27730824, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42993352, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16985175, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39300429, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45501590, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25591234, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37796476, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48442149, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54964266, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12172669, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12932497, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18324452, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55547475, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31312591, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32777827, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44666884, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26303301, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59015927, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37924368, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21962415, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17509443, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38235033, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19812480, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23831848, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54070196, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44479863, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54626539, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31429146, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14668571, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55511347, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42651174, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16562561, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31640996, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49796460, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36485494, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36483292, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38257576, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54657162, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23878650, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57638856, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51325304, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24653065, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38617237, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56329753, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49691452, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26443634, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54233548, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48386076, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41833248, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51408136, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51957002, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12935449, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21360772, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25006390, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55712696, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25125827, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45708332, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59518797, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11368259, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35148754, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18866656, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14750415, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49045376, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15378080, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22008301, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14412089, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58515368, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53263778, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54337568, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39926766, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32939485, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34264460, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11378246, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22062123, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33901491, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41625669, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22105969, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24017192, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55775981, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25329457, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23573591, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19437767, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17921962, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15098193, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44605638, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54280002, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25215832, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53580994, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13148706, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32375649, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46403826, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12062636, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49697600, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37139315, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55776571, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44205157, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16769472, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58665428, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57373987, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21899909, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53909483, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32604214, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17092787, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43839608, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28313356, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28315382, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21385706, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45901247, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27057692, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48292219, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43106352, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25652573, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29456886, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34968551, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35510165, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33022380, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33930844, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29046794, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36682452, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23145285, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57867639, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44848197, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58184260, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27991074, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18068012, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29108316, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17219826, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22817936, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43224368, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36299825, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51558616, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21075826, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17782716, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48123981, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57193230, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19815357, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26163593, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47601271, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39152359, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51225578, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27577319, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22102155, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23574313, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42357495, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32179851, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25726447, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26510425, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22386212, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14712897, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32074025, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45402702, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28168426, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12380624, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28138944, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37872993, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31724233, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14820418, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44392411, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41365176, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36646741, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37445211, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59546243, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21396151, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52723474, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23933393, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37466108, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25005744, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34191653, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45255385, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56395720, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19153482, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53295402, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13550802, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33771965, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58989971, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25768942, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53952894, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27114377, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33141776, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41107702, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36482226, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39021439, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14652273, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48403000, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26305177, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31432260, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28656823, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19613010, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11291684, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26555530, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22145529, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14082957, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18700185, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33846689, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42671948, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54017544, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58037130, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28278697, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44804810, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59364548, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45828330, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59447386, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32810895, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37702100, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13100605, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31667928, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48233732, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41914840, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25937824, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25104219, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51799274, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22976631, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49454953, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13533278, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14342337, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22850128, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46625909, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17068572, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52514114, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22821684, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52200868, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22487882, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46466666, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37201708, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43754737, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49949132, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42965806, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51615385, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23515074, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18787648, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28347668, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37995147, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11558006, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42963654, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57935888, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53147544, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12167519, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46209672, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26675726, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57713432, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52316481, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48831689, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43616838, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48663400, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56613310, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16584402, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57213125, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35757517, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16750172, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29581354, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34056085, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36535429, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24756467, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36058461, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17584516, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28906802, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22993265, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13359810, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12133398, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41844712, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31122590, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41963493, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25217761, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55577236, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21329390, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47063805, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39480403, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46958257, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15893230, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37013517, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27252072, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28159922, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12951972, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56262971, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31065683, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42511910, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44039772, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45744792, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52025644, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49409174, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48221054, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33831551, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55343798, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29573995, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22041719, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38147286, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43781427, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16302387, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54196029, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32634912, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45822013, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38444183, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35955074, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22473651, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29407863, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57806477, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31472109, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42001575, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14236407, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58912938, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19588730, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34256998, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23100318, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39259246, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43404134, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45481451, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48276247, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59072707, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48987204, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44614568, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47254678, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57336501, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49454793, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31720691, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34086705, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31243263, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57922093, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56259807, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55997826, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58512184, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53221085, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57358414, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53996171, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55506043, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35119301, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29563851, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49960831, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26402848, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31022297, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43101283, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23047457, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37070444, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53283122, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36656346, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48136839, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27009407, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36827276, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59875125, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46273049, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28918502, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34931269, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24445226, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31874092, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39986491, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45188845, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37534993, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54132188, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29686306, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43197767, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54581416, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38743505, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17129639, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41194321, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58959784, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26436451, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52591144, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11451658, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23737561, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18923648, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28918126, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49042108, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24144351, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43943251, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42454843, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56665573, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47773238, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26165303, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25605263, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24482919, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53480362, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46480088, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26506040, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59680823, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14867941, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37631664, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49703643, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38167442, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14455710, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36803008, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36165458, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42673861, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56008359, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36271407, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22980317, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11187677, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33850666, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56275471, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17880679, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27196799, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56521874, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52992005, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23436856, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21700471, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34192704, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29911442, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53350571, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29201053, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35978414, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55624532, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35086063, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28888783, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15598024, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51080782, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28218348, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11161564, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14435162, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51664386, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28745646, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43979527, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48102834, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37594270, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51677262, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56787836, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34666290, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25351272, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19233375, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43730127, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33005358, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49588922, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39847708, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52889309, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32420743, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41760180, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57427344, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58978015, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44295897, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44095815, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23814913, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51537183, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28867959, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33715145, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44700436, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22327105, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55176905, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59874836, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46924597, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26189195, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54660139, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55858280, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25903108, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18469161, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42542628, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13676155, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16593956, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21073721, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52642098, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35885714, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47193696, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22812356, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22907101, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39015313, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46679461, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49844237, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57434787, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23553777, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12687800, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21894216, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48747452, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47296816, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24686317, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13541847, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33519733, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22238207, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52355730, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32504977, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12991526, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17938866, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25962710, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39500661, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47547598, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29131834, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12051617, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34188551, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18527834, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13312393, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53595210, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21077686, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58018956, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11382132, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19072692, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17059288, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32822175, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54445236, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13054046, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33699319, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27640706, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59981663, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33169467, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47911612, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49030226, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29752814, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11117698, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39248330, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46175302, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12648818, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45231010, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47808007, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41705449, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54470536, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54915403, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26762024, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16777483, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38445353, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43294325, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27005360, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29270066, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45027653, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48042141, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46475847, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38235895, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49796250, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25979103, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52777538, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58586363, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29383267, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21972800, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45492555, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53998715, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33216274, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18142070, "t", 0, "f" );
