CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 1, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 1, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 1, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 1, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 1, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 1, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 1, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 2, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 2, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 2, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 2, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 2, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 2, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 2, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 3, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 3, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 3, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 3, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 3, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 3, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 3, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 4, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 4, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 4, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 4, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 4, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 4, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 4, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 5, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 5, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 5, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 5, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 5, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 5, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 5, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 6, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 6, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 6, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 6, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 6, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 6, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 6, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 7, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 7, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 7, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 7, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 7, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 7, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 7, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 8, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 8, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 8, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 8, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 8, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 8, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 8, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 9, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 9, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 9, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 9, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 9, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 9, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 9, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 10, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 10, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 10, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 10, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 10, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 10, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 10, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 11, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 11, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 11, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 11, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 11, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 11, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 11, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 12, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 12, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 12, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 12, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 12, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 12, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 12, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 13, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 13, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 13, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 13, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 13, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 13, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 13, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 14, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 14, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 14, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 14, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 14, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 14, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 14, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 15, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 15, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 15, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 15, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 15, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 15, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 15, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 16, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 16, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 16, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 16, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 16, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 16, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 16, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 17, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 17, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 17, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 17, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 17, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 17, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 17, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 18, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 18, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 18, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 18, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 18, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 18, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 18, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 19, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 19, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 19, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 19, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 19, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 19, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 19, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 20, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 20, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 20, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 20, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 20, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 20, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 20, 62 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 21, 56 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 21, 57 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 21, 58 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 21, 59 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 21, 60 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 21, 61 );
INSERT INTO relacion_Grupos_tienen_Materias (foranea_id_grupo, foranea_id_materia)
VALUES ( 21, 62 );
