CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 13319614, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 54492320, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 48914198, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 58907349, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 16974140, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 11826572, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 29087392, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 59027194, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 46174580, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 14068886, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 44565123, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 12799637, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 14060135, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 53296183, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 55775602, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 33020100, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 17171024, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 36546539, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 52287901, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 18660802, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 31504647, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 28155750, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 19689297, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 52437950, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 17096824, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 11523875, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 49560128, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 22633528, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 18299520, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 46032641, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 38730497, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 44694459, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 28419910, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 33711503, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 37274767, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 52274398, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 57131228, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 52681074, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 12036194, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 55725544, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 21345782, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 51450612, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 27839957, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 17326932, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 32895037, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 55128544, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 46861313, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 49661174, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 51146930, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 21540037, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 24099332, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 47676880, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 49130284, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 39788047, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 34796928, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 52031851, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 39234911, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 53847203, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 22302682, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 12853451, 1 );
INSERT INTO Relacion_Docente_Trabaja_Instituto (foranea_CI_docente, foranea_id_instituto)
VALUES ( 38434152, 1 );
