CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 45433391, 56, 1, 1 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 43672062, 57, 1, 1 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 25002344, 58, 1, 1 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26528925, 59, 1, 1 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 18022511, 60, 1, 1 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 21619741, 61, 1, 1 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 19483722, 62, 1, 1 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29327130, 56, 1, 2 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 52471970, 57, 1, 2 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29097533, 58, 1, 2 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26890522, 59, 1, 2 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 19483722, 60, 1, 2 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 13418311, 61, 1, 2 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 25002344, 62, 1, 2 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 54655578, 56, 1, 3 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 13070739, 57, 1, 3 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 27517725, 58, 1, 3 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 15002415, 59, 1, 3 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 19483722, 60, 1, 3 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 54655578, 61, 1, 3 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 49442582, 62, 1, 3 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 42975940, 56, 1, 4 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 27517725, 57, 1, 4 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26890522, 58, 1, 4 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 46024414, 59, 1, 4 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32400985, 60, 1, 4 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 53334640, 61, 1, 4 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 52471970, 62, 1, 4 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 14136712, 56, 1, 5 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32708955, 57, 1, 5 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 54655578, 58, 1, 5 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 19483722, 59, 1, 5 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29097533, 60, 1, 5 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 21619741, 61, 1, 5 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 21619741, 62, 1, 5 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 27517725, 56, 1, 6 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 14136712, 57, 1, 6 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 41538775, 58, 1, 6 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 53334640, 59, 1, 6 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26528925, 60, 1, 6 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 24647795, 61, 1, 6 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 18022511, 62, 1, 6 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 15533311, 56, 1, 7 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 37376682, 57, 1, 7 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 27517725, 58, 1, 7 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 23153393, 59, 1, 7 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26528925, 60, 1, 7 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 15002415, 61, 1, 7 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 46024414, 62, 1, 7 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 36277730, 56, 1, 8 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 58405965, 57, 1, 8 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 17563497, 58, 1, 8 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 56797776, 59, 1, 8 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26528925, 60, 1, 8 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26032281, 61, 1, 8 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 11800481, 62, 1, 8 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26032281, 56, 1, 9 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 36277730, 57, 1, 9 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 52423246, 58, 1, 9 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 28987452, 59, 1, 9 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 23133836, 60, 1, 9 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 52471970, 61, 1, 9 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 41538775, 62, 1, 9 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29097533, 56, 1, 10 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 49442582, 57, 1, 10 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 44252069, 58, 1, 10 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 18022511, 59, 1, 10 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 24647795, 60, 1, 10 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 44252069, 61, 1, 10 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 45213664, 62, 1, 10 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 55267378, 56, 1, 11 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 58405965, 57, 1, 11 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 11800481, 58, 1, 11 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26890522, 59, 1, 11 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 39430050, 60, 1, 11 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 13070739, 61, 1, 11 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 42975940, 62, 1, 11 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26890522, 56, 1, 12 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 14174625, 57, 1, 12 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 17563497, 58, 1, 12 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 42975940, 59, 1, 12 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26528925, 60, 1, 12 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32400985, 61, 1, 12 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32224450, 62, 1, 12 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32224450, 56, 1, 13 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29097533, 57, 1, 13 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 18022511, 58, 1, 13 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 52471970, 59, 1, 13 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32224450, 60, 1, 13 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 56797776, 61, 1, 13 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 41538775, 62, 1, 13 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29097533, 56, 1, 14 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 27726734, 57, 1, 14 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 13070739, 58, 1, 14 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 14174625, 59, 1, 14 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32400985, 60, 1, 14 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 27726734, 61, 1, 14 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 18022511, 62, 1, 14 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26890522, 56, 1, 15 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26528925, 57, 1, 15 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 23164077, 58, 1, 15 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29327130, 59, 1, 15 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 52423246, 60, 1, 15 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 24923028, 61, 1, 15 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 41538775, 62, 1, 15 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 14174625, 56, 1, 16 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 23153393, 57, 1, 16 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 45913022, 58, 1, 16 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32400985, 59, 1, 16 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 54655578, 60, 1, 16 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 47271280, 61, 1, 16 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26032281, 62, 1, 16 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 39430050, 56, 1, 17 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 45913022, 57, 1, 17 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29327130, 58, 1, 17 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 49800154, 59, 1, 17 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 58405965, 60, 1, 17 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 49800154, 61, 1, 17 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 15533311, 62, 1, 17 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 15002415, 56, 1, 18 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 31455343, 57, 1, 18 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 37946782, 58, 1, 18 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32400985, 59, 1, 18 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 56797776, 60, 1, 18 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 18022511, 61, 1, 18 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 45433391, 62, 1, 18 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 45213664, 56, 1, 19 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26890522, 57, 1, 19 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 37408255, 58, 1, 19 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 17563497, 59, 1, 19 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 23133836, 60, 1, 19 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 46024414, 61, 1, 19 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 54655578, 62, 1, 19 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 18022511, 56, 1, 20 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 26032281, 57, 1, 20 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 27726734, 58, 1, 20 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 27726734, 59, 1, 20 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 37946782, 60, 1, 20 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 21619741, 61, 1, 20 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 13418311, 62, 1, 20 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 46024414, 56, 1, 21 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 32400985, 57, 1, 21 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 18022511, 58, 1, 21 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29097533, 59, 1, 21 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 58405965, 60, 1, 21 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 56797776, 61, 1, 21 );
INSERT INTO relacion_Profesor_Materias_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_instituto, foranea_id_grupo)
VALUES ( 29327130, 62, 1, 21 );
