CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 48539920, 56, 1, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 25845491, 57, 1, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 35965500, 58, 1, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 19461693, 59, 1, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 52327115, 60, 1, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 27854953, 61, 1, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 43045819, 62, 1, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 24723676, 56, 2, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 17638666, 57, 2, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 32285151, 58, 2, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 57516402, 59, 2, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 58931269, 60, 2, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 51260859, 61, 2, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 35965500, 62, 2, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 34883276, 56, 3, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 37001265, 57, 3, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29734048, 58, 3, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 26578635, 59, 3, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 34883276, 60, 3, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 37589904, 61, 3, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 52272964, 62, 3, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 14095708, 56, 4, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 15618185, 57, 4, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 38349084, 58, 4, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 47231200, 59, 4, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29734048, 60, 4, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 54530570, 61, 4, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 35664782, 62, 4, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 27977492, 56, 5, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29734048, 57, 5, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 26578635, 58, 5, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29278397, 59, 5, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 26298685, 60, 5, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 48841660, 61, 5, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 46501353, 62, 5, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 41025178, 56, 6, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 48841660, 57, 6, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 52272964, 58, 6, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29278397, 59, 6, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 17638666, 60, 6, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 21296892, 61, 6, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 12004551, 62, 6, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29278397, 56, 7, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 51271254, 57, 7, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 54530570, 58, 7, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 57516402, 59, 7, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 18700066, 60, 7, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29278397, 61, 7, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 47231200, 62, 7, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 58931269, 56, 8, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 16547543, 57, 8, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 17638666, 58, 8, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29734048, 59, 8, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29278397, 60, 8, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 41025178, 61, 8, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 19461693, 62, 8, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29278397, 56, 9, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 44789947, 57, 9, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 27977492, 58, 9, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 25845491, 59, 9, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 44527549, 60, 9, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 44527549, 61, 9, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 57504859, 62, 9, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 47104659, 56, 10, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 17638666, 57, 10, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 18700066, 58, 10, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 37001265, 59, 10, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 51260859, 60, 10, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 54530570, 61, 10, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 32001646, 62, 10, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 25845491, 56, 11, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29278397, 57, 11, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 46325050, 58, 11, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 24193697, 59, 11, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 24193697, 60, 11, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 37799315, 61, 11, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 15618185, 62, 11, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 52327115, 56, 12, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 17638666, 57, 12, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29734048, 58, 12, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 48841660, 59, 12, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 27854953, 60, 12, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 32513073, 61, 12, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 37799315, 62, 12, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 49351921, 56, 13, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 47231200, 57, 13, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 32285151, 58, 13, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 52327115, 59, 13, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 17638666, 60, 13, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 59822764, 61, 13, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 46325050, 62, 13, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 52327115, 56, 14, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 13407922, 57, 14, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 52272964, 58, 14, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 21755307, 59, 14, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 27854953, 60, 14, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 13941986, 61, 14, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 46501353, 62, 14, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 34883276, 56, 15, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 51260859, 57, 15, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 27977492, 58, 15, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 37001265, 59, 15, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 21755307, 60, 15, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 34883276, 61, 15, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 24723676, 62, 15, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 35965500, 56, 16, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 16547543, 57, 16, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 58931269, 58, 16, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 32001646, 59, 16, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 16547543, 60, 16, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 18700066, 61, 16, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 48841660, 62, 16, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 44527549, 56, 17, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 14893499, 57, 17, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 55893204, 58, 17, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 47104659, 59, 17, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 44527549, 60, 17, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 25208079, 61, 17, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 46501353, 62, 17, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 27977492, 56, 18, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 25208079, 57, 18, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 19461693, 58, 18, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 48539920, 59, 18, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 26298685, 60, 18, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 53978189, 61, 18, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 37001265, 62, 18, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 44527549, 56, 19, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 53978189, 57, 19, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 17638666, 58, 19, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 32285151, 59, 19, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 24193697, 60, 19, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 29090961, 61, 19, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 27977492, 62, 19, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 14893499, 56, 20, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 27854953, 57, 20, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 53978189, 58, 20, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 32285151, 59, 20, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 13407922, 60, 20, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 59822764, 61, 20, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 25208079, 62, 20, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 49351921, 56, 21, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 55893204, 57, 21, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 51271254, 58, 21, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 24723676, 59, 21, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 46325050, 60, 21, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 54530570, 61, 21, 1 );
INSERT INTO Relacion_Docente_Asignatura_Grupos (foranea_CI_docente, foranea_id_asignatura, foranea_id_grupo, foranea_id_instituto)
VALUES ( 45513604, 62, 21, 1 );
