CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29155814, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58544272, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14464515, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59505560, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22977083, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14327074, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26195396, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12226866, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56799865, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59605045, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46160763, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46279770, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47747188, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43970399, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42308002, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16264228, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47615167, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56169488, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47266839, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12597760, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57651600, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34592122, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52350962, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13453733, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46921200, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59805958, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32026937, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25445625, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55091705, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26146179, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31516513, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51342881, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19786548, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26845066, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55622170, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24682800, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22211372, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26244872, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26996067, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41961605, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26421282, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29404190, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44529763, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59986180, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16520903, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57612373, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54165725, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33389520, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36483189, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12886145, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14452893, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24960921, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36440113, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58540840, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28402248, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26724070, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47314349, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39377688, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55282471, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36539334, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52726711, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34232093, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11217703, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14025791, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57985601, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42803858, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15785625, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13085760, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29823344, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37997311, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36198857, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25114529, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29880613, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11210216, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28822509, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57597397, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55935927, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23953004, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53306417, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42830059, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23250939, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43213026, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51582586, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42028751, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29950581, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14644228, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29593349, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58632916, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29794212, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21743613, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19962409, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41950517, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44002979, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39583968, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53248142, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24045472, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49583659, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17369685, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29922405, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33914349, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39604998, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46733655, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31820615, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35264386, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13414280, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28397328, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47869015, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41610014, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16816154, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46202276, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53184732, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26354833, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42028347, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24152801, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55988338, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12960216, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48665129, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54516512, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41730476, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44899118, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21430935, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49558020, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23981287, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31773143, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27692878, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39016618, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31853478, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54380571, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36433930, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54535611, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17546954, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51508213, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31164045, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32669278, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37002764, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57956747, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38880949, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59319402, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24089696, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13054717, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56182317, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37235781, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34565909, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54540272, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29749869, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13964893, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46088509, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29864704, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55137775, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41636804, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48515821, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15064035, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59208588, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48132708, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58076912, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38747169, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34675926, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26791358, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56570853, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44177455, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57130876, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54840745, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54940509, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24496582, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33855371, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48115873, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16273283, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53048972, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47948540, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43518890, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22354403, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19998587, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13070347, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49962306, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14176667, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18842171, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59156157, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41398967, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44048022, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41208645, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49342320, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25255997, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58290190, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15462869, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12327840, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13657426, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38038928, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59073723, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59352092, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18867462, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18879849, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19381471, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39829095, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31205548, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24318716, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14876865, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18346581, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52071364, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34006723, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18661323, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39195109, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39847560, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37852765, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48397001, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15972834, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14276249, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48625650, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24059164, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11704968, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31906041, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25109617, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25493127, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29428841, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36988634, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27702895, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56562074, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29062136, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22209854, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58985254, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24808810, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23324217, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31081699, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39642986, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58657730, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29757739, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36577128, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31932925, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53942653, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34199893, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29197187, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42603484, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35824615, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42122260, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28489400, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53885069, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46985527, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57025746, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49665700, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46009214, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43695399, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25951343, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45923837, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52207060, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44019237, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28208793, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27718115, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19650333, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16854744, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13608180, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28296526, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29930698, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28477528, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45550751, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39260748, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22117584, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23223885, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52855699, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22694837, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48851334, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55731228, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45399034, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27770503, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59080401, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11530280, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13810561, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32663713, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45036884, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23281954, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52633180, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14923224, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38691049, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38856938, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56136910, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53348019, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11991616, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56522260, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48806323, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43813658, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22363496, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23862653, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39864906, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18699879, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25161497, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25589841, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51877313, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33276404, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46789228, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38598960, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38641185, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34608422, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36377243, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21519846, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35243502, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46864456, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45621510, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51823475, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47676482, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57652494, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41999173, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36531439, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37425588, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41982677, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44371035, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26897887, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58645074, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56232518, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23335377, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22350009, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56846406, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21933078, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16525395, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55278319, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37253422, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19502077, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52061935, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11273062, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34429995, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56171003, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13963491, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39399773, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17467526, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11413096, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43757030, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53222421, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36072833, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39128984, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54573176, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11205558, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36083222, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37352583, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28437350, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46209923, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23810202, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32751786, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35806689, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26611114, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25172961, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41353250, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33442118, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43572587, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53226922, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45160091, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55018232, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48589696, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48678334, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27128445, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29143603, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51405689, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38073362, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45375173, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59315644, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45755620, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59982247, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19697026, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33807023, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14163775, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42271116, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12921070, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46995990, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34799287, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26142060, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47768332, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48428169, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49957438, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46910281, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38741999, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54877861, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41030682, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35458521, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46776239, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36622824, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54597805, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55858086, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13555250, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18833229, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13609827, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22117528, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14036378, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35159319, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14338968, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54742525, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22007705, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47063883, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15292767, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58586357, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21791579, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34802206, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43617569, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22235932, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43460023, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55624316, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18497720, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16543735, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31180120, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57383065, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11362164, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15877274, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43338648, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55981136, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24429947, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36983941, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19521756, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26768448, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56371988, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13623493, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35824239, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53488994, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18163058, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13492606, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28463820, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35355038, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29126176, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31104398, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54398407, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19504906, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43628033, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19828948, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49817406, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45684639, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43638105, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59312799, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55196434, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31195452, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54173350, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22577875, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31442627, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52777453, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39839844, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23472125, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31634137, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23157327, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14263131, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52350699, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58562684, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53659733, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44666254, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19021988, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22899314, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49395098, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58770291, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19280776, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32640276, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22106941, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25842825, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39784041, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58023614, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47660980, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16802252, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39479252, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58374001, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49440227, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24975093, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42330247, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12151590, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29388546, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28461571, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23469829, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43402089, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29836361, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49130052, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31837666, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39410117, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13859440, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51947275, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28268218, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59545108, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53226358, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38760242, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15932876, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39208736, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18328793, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51026960, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48785939, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17064184, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49159010, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57153573, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27456668, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34056869, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39245275, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22674665, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46236168, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22896782, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57294242, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53075684, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46564171, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36789753, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52240434, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28107189, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21251301, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26483921, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33843085, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22477005, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55464182, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25107879, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17772707, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21543841, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18824258, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12226082, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48267931, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58107547, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17910567, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18920953, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28975928, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55024126, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32513277, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26249026, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33459329, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32013891, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35916747, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51791341, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27670363, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12240943, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36649442, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33943065, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24936192, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51269128, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46915350, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46227238, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57908370, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14632227, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23581552, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59773777, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24609575, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44974960, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12892863, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17009772, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58468589, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31749201, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33815078, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52942248, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54122555, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16797285, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37312321, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13910046, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38054376, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35153779, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13647439, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59697733, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53525582, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33821809, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51185091, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27920847, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34257936, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41238735, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59691240, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29503524, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42770758, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44488765, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22539906, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11546447, "t", 0, "f" );
