CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49792505, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31987180, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27943538, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54824529, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51617286, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39864912, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54585058, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43937113, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33943413, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42576413, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46741531, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41833903, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24677766, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49150149, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43696995, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35120320, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21201209, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55718305, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54986317, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44721668, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44105779, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14819342, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58786674, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18678578, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35751654, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54596544, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14178762, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43288958, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13476220, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33594373, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11022489, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53978145, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37281990, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55360219, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57734125, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26141129, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54580202, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16111423, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19301289, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57031787, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32524161, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14512633, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27313725, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34098223, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21933090, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49174345, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15467972, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57615513, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23076509, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53817044, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23129304, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58802535, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57431042, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29649403, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47720407, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47516250, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54684012, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59726702, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32829656, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57689388, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24166929, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28344951, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49469508, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55682996, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18010980, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29891961, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56464553, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12370320, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31317109, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25322716, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43954139, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42178736, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25934816, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48745169, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29656216, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38180008, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57833430, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13980150, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29688360, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22867771, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48704191, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48156534, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26428230, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56848028, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41867124, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54368834, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28719217, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25026948, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25071006, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18414100, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28111382, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37066871, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38153506, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41321946, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52479687, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36621369, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59882966, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12906955, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55200639, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53013854, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11117290, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53292171, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55670951, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25360306, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18869868, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31200510, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41150696, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36556968, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14348319, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22494071, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47975406, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22061141, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36903232, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16522337, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45952854, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17654490, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14469822, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52186905, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55466237, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42259598, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28239304, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55280508, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42339124, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33150236, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59377775, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52577095, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28151607, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39513525, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18437186, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11275515, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42703016, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18613031, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14459647, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56675372, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44003280, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28967202, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59793927, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42175198, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38444406, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45121510, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48884959, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35300776, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27973991, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46612556, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46964602, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11786261, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29546619, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54003909, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23716840, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24676693, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54300323, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43646508, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29371244, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16189921, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45651694, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56383428, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18682549, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57394385, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49424192, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48715085, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42471217, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25428245, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54782345, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23029625, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11194010, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25631943, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53207077, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26882527, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18376176, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11264160, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24384937, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22324733, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24223171, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51741459, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16532584, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56636700, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16375277, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21585192, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48628668, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47789019, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15196539, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19048380, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43431341, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53738042, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32405236, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25887203, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21874668, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33215907, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27713739, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22919594, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11786368, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22737560, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24430035, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27483869, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45012810, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27656521, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35835866, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13112593, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12102486, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47783275, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17346041, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22690778, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53192204, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43127954, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43776123, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17222188, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27486435, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48626143, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27342639, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45990422, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48039334, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33674329, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56389143, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41424586, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19131325, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39237004, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44470986, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31228007, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11514973, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42944652, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46317691, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24052332, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47795301, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44078269, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45522120, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19571911, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32647876, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27887459, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14808408, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23412779, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29769279, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57514614, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27630286, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55696694, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25666760, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29808207, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49122132, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35387643, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25550551, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51939430, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55758761, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32691231, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45164047, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58945735, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15571848, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14373506, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35077707, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12514968, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35508528, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54233651, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36806737, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21139195, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12016007, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35517486, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12164711, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11457464, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58675409, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21345174, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25784748, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44723218, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36939194, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43556349, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33803118, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38586890, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44106171, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35454666, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29740158, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25336129, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54948250, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42304341, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42507046, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57354004, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32918429, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37489695, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17868998, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39703071, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46718364, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27339593, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38631267, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51138101, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33130274, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27769164, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41315579, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24812740, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44973972, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11799272, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56846359, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51279507, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41658870, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15658892, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35742633, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36703749, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27105538, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14335091, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29273488, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43554175, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41252420, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58467983, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11064815, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33995864, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46929183, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11950955, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29494153, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23866063, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26231601, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44841791, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32180165, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24574524, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26044674, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35127049, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57278662, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39638448, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17895848, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46957457, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32172762, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28492502, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16272803, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44747470, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45462647, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44309086, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39192066, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35649623, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22444383, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52157944, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18147688, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24454087, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19508394, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59588914, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38457116, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23479145, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25922401, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44045042, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27943384, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17490232, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18741802, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24418100, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49876074, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14222812, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11207330, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33276313, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31496703, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31687689, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51211955, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47685908, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19561225, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14686654, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56733528, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25538325, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18291578, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51445368, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24795352, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41181984, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12248553, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46068246, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54172469, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38509042, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55248940, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37292981, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29177078, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17351505, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14110035, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27256846, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45014432, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58397623, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22239552, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15307574, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12065365, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13547904, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25056436, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19257662, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47323291, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34575106, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18050976, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22725973, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15018644, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28615554, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17619266, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46617954, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27510216, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36752308, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26647991, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52942113, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23102645, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15140035, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54093069, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34498118, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18249622, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55837440, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51050103, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58746860, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14183878, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43703227, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32514174, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43825110, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46477271, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54121636, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23444544, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53879454, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35980675, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39584031, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41739745, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56633877, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55108134, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55912399, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58557625, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41987809, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49872329, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26044408, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22313300, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32667242, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44631374, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28846238, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38541791, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15241934, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49852088, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37618490, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27439272, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24258374, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27493436, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56028355, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48430665, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21849437, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13119422, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55870977, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13406257, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43813216, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24853495, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33174852, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59190224, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39805441, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32458603, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26274683, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42404622, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45009235, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21272709, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34288393, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16592322, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35300936, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42438360, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56205395, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56178675, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14228985, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59600415, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26992196, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42820379, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58315201, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43301431, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44798833, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46578073, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17282863, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15524942, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16436237, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42230104, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37538212, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41243415, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28680793, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13028178, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31382934, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41464312, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26142872, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14790821, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27185918, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19650719, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43911408, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44994433, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56078178, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36193584, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33870167, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14267789, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53809431, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33545861, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45214925, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34038009, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25184326, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48611695, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44002151, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15441502, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41883403, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34125589, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54949856, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56848818, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48517669, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52981525, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23052739, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27911309, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39326140, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36011552, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54202266, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13290892, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49666055, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17597715, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41317420, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25387736, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41276212, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52644820, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37991680, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31505594, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57192082, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37386657, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24984274, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45191282, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43694709, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33850638, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49805267, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45400936, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27454466, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53798692, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25337957, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55657141, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46408252, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35111832, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39995484, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44810221, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58868167, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35341409, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26003957, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38106882, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11420194, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12015906, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18306664, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16376469, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24972427, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38727094, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51926015, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22003094, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38211859, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25607136, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16209264, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25013868, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28899768, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15699616, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38411621, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21960144, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28583646, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31551242, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18632550, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38209018, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27042423, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27134721, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39110531, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51637000, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41676709, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53443873, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15879818, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33076256, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55403431, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28082818, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42471245, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24123072, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13454577, "t", 0, "f" );
