CONNECT TO 'gestion_utu@miServidor' USER 'XXXNOMBREUSUARIOXXX'  USING 'XXXPASSWORDXXX';


INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15033399, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56140260, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13713840, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37497418, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35092220, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24133229, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22157815, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49697274, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35057109, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17488974, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16240373, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22632063, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31839539, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27658961, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51438599, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19953234, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23863895, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47512561, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14723333, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46615661, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18287024, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51080657, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45131789, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13081184, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56475663, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21850252, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49669659, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15397628, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25627944, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55024671, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38090996, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47581580, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57502685, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11386809, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58148800, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37124914, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44387690, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43724772, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18763038, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33178325, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23250917, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37523617, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37954179, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35206267, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22190643, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29947213, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44545995, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18652318, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31833096, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28744175, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24790487, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51310668, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13095359, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55738981, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49695981, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26933186, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43137383, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35985835, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41704990, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47688994, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57075898, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51128261, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27891442, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58049959, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58925212, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35109671, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53040726, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14733370, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47101403, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27989186, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35115399, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39510181, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21302249, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19235759, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24211374, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21261382, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26835671, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55645457, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21672898, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12126472, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44621218, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53801495, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42693986, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43331929, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17068908, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49096187, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59768257, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15979183, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26387072, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48458215, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29496173, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14285549, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57406532, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34213091, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14619257, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17254969, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43844394, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53807944, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19783160, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34788020, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48535617, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21310147, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59976507, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34881557, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19219709, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13077505, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47957630, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21455577, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27288570, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18296512, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14895613, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54228692, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22145046, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52207703, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29883449, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52840232, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25003627, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26336738, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33469394, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38039671, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39536426, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12144141, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24854041, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37244263, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26723361, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12665254, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31422875, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22802529, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14417926, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46394875, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11612074, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17762287, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32877233, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59075113, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31403055, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44331259, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28685226, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45559252, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25181653, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24553223, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51370309, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41685877, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44196457, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58053265, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56998075, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51963902, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49302754, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21225994, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51293690, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11130696, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22360400, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34599625, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52519089, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52107018, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47307752, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58413863, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15150185, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15428720, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27632858, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55746049, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31426912, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43615107, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44561321, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59869996, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44049907, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12411594, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59042792, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51711610, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41728077, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52767240, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54138637, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33814591, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36606454, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22751681, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38220262, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56476623, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33052903, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48455605, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33784017, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42329466, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47328097, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17544398, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18067767, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38540010, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48129640, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14762444, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15248192, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32644777, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14965064, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44558633, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17417731, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22547105, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46938085, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46238815, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57871230, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22878449, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47619878, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34865369, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16112154, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55687651, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14021949, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25941782, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49151745, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45520683, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28214762, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11120433, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34781709, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34879534, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45321558, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33709029, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39893581, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13330432, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52351041, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11955052, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36898635, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37150525, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25701883, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18967298, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19884990, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57113060, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23508067, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33674846, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11331519, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32761983, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46560006, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56047608, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46202555, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14303282, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14313768, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44604048, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32351857, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19767502, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28950386, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42453639, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12475407, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26711100, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42503460, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32135182, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49083182, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35642584, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42965276, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52933318, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55279329, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52839893, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54448181, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37079600, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34360024, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14045402, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53059060, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22214700, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15703297, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12205838, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16968541, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22907509, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45869358, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12638605, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47261431, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51794569, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32583698, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32591596, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12850863, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14415439, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29686168, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54213730, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52695722, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11838363, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44886630, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51539642, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33628897, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29941526, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53264346, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19824748, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48044973, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18721561, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38342064, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54896512, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24933106, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28172823, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32544452, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24331009, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37284005, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39791440, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21075804, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39482360, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19715327, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53030698, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22331803, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32185096, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24880890, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37407126, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34440456, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32698825, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13675628, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11440883, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47302978, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12129888, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55292725, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15321792, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19760457, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25395480, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27816852, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26222602, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29138882, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21088235, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36233970, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18244989, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12275839, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16317794, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21156694, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55482732, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16919108, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35431743, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42572843, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47508136, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42183256, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17814561, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29285649, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59396909, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52437897, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54567583, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27067457, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59809807, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48458237, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39230501, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56137986, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27911343, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48770497, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52755512, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46423446, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29123500, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35654949, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52360181, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29580429, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58542882, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48544462, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42995015, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21446095, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36095267, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53924326, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14614871, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18161317, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16042571, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41400114, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54177992, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43223091, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59579090, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13982471, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56160545, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53489716, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29877298, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46590685, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54020925, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14829652, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44571205, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19224752, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12166292, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48593582, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46407286, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27777288, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43530515, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25792000, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44830772, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35703635, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28812926, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34171845, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33888974, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15910010, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14822808, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39335600, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22033554, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44038411, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49834507, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33873028, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46008953, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36592754, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15142334, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28258209, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41256341, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16397447, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48147632, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56899823, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43778579, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37814620, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41391072, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48074198, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58738956, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56446163, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43217555, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17208346, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16797564, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27630593, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26402440, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58632386, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11020005, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12546620, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31207386, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56399356, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35698890, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43894872, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22550912, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34047268, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25246863, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24134029, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13721334, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51410472, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31193824, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45025194, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54359136, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11714535, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57479331, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45114070, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17953878, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32723531, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26066383, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 25179511, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45462073, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12310526, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12098695, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26108608, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49160948, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36468519, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51606756, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31166554, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49823475, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59833294, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38336374, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37004342, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55921031, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 13405106, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44804876, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38318069, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47587603, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15491864, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21159191, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53160097, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27644241, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45814717, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56959522, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28849070, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 42906153, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17460299, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26128808, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15976921, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54550877, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38305531, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 33386158, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29263297, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59696416, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56408636, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 28282022, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24867983, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 55664788, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 17895484, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32316350, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19950066, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54182274, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49126558, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44146082, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57218573, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19424665, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32712697, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11054458, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31763548, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36156590, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43061433, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52579899, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36033164, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39816783, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53342532, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21574587, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58869519, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58068810, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43295595, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27946687, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51735286, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41500423, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44226737, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 37720299, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14594431, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39057965, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16500957, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27602906, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15719454, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16328490, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 24382848, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11093597, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14685008, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 59409398, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19669956, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 19019573, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31389998, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48760002, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21566532, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51364443, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 43776355, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47446003, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22955506, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44689525, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54800282, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 29499385, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39370050, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14696447, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 23663415, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 58440848, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45759911, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57589148, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 36890166, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16232340, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 15883726, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 53978123, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 39592280, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27755018, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14305280, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 45205653, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18845377, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38713299, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 54201262, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 57243516, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 22276847, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 38740939, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49258717, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 34718461, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49079763, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 16505640, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44526341, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 26224177, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 56295938, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 27784160, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49784964, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 31014935, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 18630803, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12384523, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41793222, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41826827, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 46280567, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 52494887, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51635717, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 44703438, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 47036933, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 14823868, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 49225556, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 11730488, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 51176995, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 12132388, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 32678885, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48713112, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 35256507, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 41812072, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 21795462, "t", 0, "f" );
INSERT INTO Profesor (CI_alumno, hace_proyecto, nota_final, baja)
VALUES ( 48517346, "t", 0, "f" );
